apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal20
spec:
  teamId: "ACID"
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  volume:
    size: 1Gi
  postgres_exporter:
    image: "wrouesnel/postgres_exporter:latest"
    cpu_request: "100m"
    memory_request: "50Mi"
    configmap_name: postgres-exporter-configmap
    database: foo
  numberOfInstances: 1
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    foo_user:
  
  #databases: name->owner
  databases:
    foo: zalando
  postgresql:
    version: "10"
  patroni:
    ttl: 3000