apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: operator
      containers:
      - name: postgres-operator
        image: postgres-operator:v1
        imagePullPolicy: IfNotPresent
        env:
        # uncomment to overwrite a similar setting from operator configmap
        # if set to the empty string, watch the operator's own namespace
        # if set to the "*", listen to all namespaces
        # - name: WATCHED_NAMESPACE
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: metadata.namespace
        - name: CONFIG_MAP_NAME
          value: "postgres-operator"
